Py age new cases writer
SABS-R3-Epidemiology/epiabm pull request #145
Opened 2022-09-12 14:01 UTC by NicholasFan235

## Summary

Age stratified new cases writer for comparison to covidsim

## Checklist

- [ ] All new functions have docstrings in the correct style
- [ ] I've verified the complete docs build locally without errors
- [ ] I've maintained 100% coverage (please mention any 'no cover' annotations explicitly)
- [ ] I've unit-tested all new methods directly

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the wiki with new parameters/model functionality

## Closing issues

Closes #141

2022-09-12 14:53 UTC, KCGallagher requested changes
Tiny style changes, particularly to match the style of docstrings elsewhere

2022-09-12 14:53 UTC, KCGallagher commented on pyEpiabm/pyEpiabm/output/age_stratified_new_cases_writer.py
> +                   person.infection_start_time > (t-1):
```suggestion
                if (person.infection_start_time is not None
                    and person.infection_start_time > (t-1)):
```
I think this is nicer, but happy either way

2022-09-14 09:25 UTC, patricia-lamy approved these changes

2022-09-26 10:28 UTC, KCGallagher approved these changes

2022-09-26 11:33 UTC, merged