Compression of infection history csv files
SABS-R3-Epidemiology/epiabm pull request #252
Opened 2024-01-23 06:57 UTC by abbie-evans

## Summary

- Use a compression method to reduce the storage space
- Be able to compress to and extract from zip csv files
- Enable the compression to be activated and deactivated
- Ran on two example simulations

## Checklist

- [ ] All new functions have docstrings in the correct style
- [ ] I've verified the complete docs build locally without errors
- [ ] I've maintained 100% coverage (please mention any 'no cover' annotations explicitly)
- [ ] I've unit-tested all new methods directly

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the wiki with new parameters/model functionality

## Closing issues

Closes #250

2024-01-23 14:55 UTC, KCGallagher requested changes
Great work, and some really nice testing! A few small changes, and some suggestions about the kinds of files we want to merge onto main (avoiding large or binary files).

2024-01-23 14:55 UTC, KCGallagher commented on pyEpiabm/pyEpiabm/tests/test_unit/test_routine/test_simulation.py
> +            del test_sim.writer
Could just delete whole `test_sim` object to ensure all writers are deleted

2024-01-23 14:55 UTC, KCGallagher commented on pyEpiabm/pyEpiabm/tests/test_unit/test_routine/test_simulation.py
> +                mock_status_writer.compress.assert_called_once()
Would it be possible here to test that it was called with the right data? If this is not easy then don't worry about it

2024-01-23 14:55 UTC, KCGallagher commented on python_examples/basic_infection_history_simulation/simulation_outputs/inf_status_history.gz
I'm not sure we need to commit binary files like this?

2024-01-23 14:55 UTC, KCGallagher commented on python_examples/gibraltar_example/simulation_outputs/with_intervention/demographics.csv
This file is quite big - do we need to include it in the main repository that people might want to download? I think it is easy to regenerate, and it would be fine to only include a small demographics file in this PR (from a toy population example)

2024-01-23 14:55 UTC, KCGallagher commented on python_examples/gibraltar_example/simulation_outputs/without_intervention/demographics.csv
Ditto re demographics files, esp as this is a duplicate file

2024-01-23 16:07 UTC, abbie-evans commented on python_examples/basic_infection_history_simulation/simulation_outputs/inf_status_history.gz
As in do not have them within the repository?

2024-01-23 16:08 UTC, abbie-evans commented on python_examples/gibraltar_example/simulation_outputs/with_intervention/demographics.csv
I can remove this file and the other one for no interventions from this example

2024-01-23 20:07 UTC, abbie-evans commented on pyEpiabm/pyEpiabm/output/_csv_dict_writer.py
> +        output_filepath = f"{self.filepath_without_extension}.gz"
Ok, will change this

2024-01-23 21:54 UTC, abbie-evans commented on pyEpiabm/pyEpiabm/tests/test_unit/test_output/test_csv_dict_writer.py
> +    def test_compress(self, mock_mkdir, mock_remove, mock_read, mock_to_csv):
I have attempted to write a test for this but haven't been successful (most likely due to the mocks)

2024-01-24 15:51 UTC, KCGallagher approved these changes
Great work - especially on some difficult mocking in the tests!

2024-01-24 15:51 UTC, KCGallagher commented on python_examples/basic_infection_history_simulation/simulation_flow.py
> +                      "compress": False}  # Set to True if compression wanted
```suggestion
                      "compress": False}  # Set to True if compression desired
```
Tiny thing but this wording seems more standard (but I'm really sorry if this takes you over the line limit and fails flake8

2024-01-24 16:42 UTC, merged