infectivenesss to infectiousness
SABS-R3-Epidemiology/epiabm pull request #42
Opened 2022-01-19 15:41 UTC by Elizabeth-Hayman

2022-01-19 15:42 UTC, Elizabeth-Hayman commented
Sticking with infectiousness in line with CovidSim. Haven't changed anything in the C++ backend

2022-01-19 15:44 UTC, KCGallagher requested changes
I can't decide if I love or hate the name of this branch

2022-01-19 15:44 UTC, KCGallagher commented on pyEpiabm/pyEpiabm/routine/covidsim_helpers.py
> +        :return: infectiousness parameter of household
```suggestion
        :return: Infectiousness parameter of household
```

2022-01-19 15:48 UTC, KCGallagher approved these changes

2022-01-19 15:55 UTC, KCGallagher commented
> Sticking with infectiousness in line with CovidSim. Haven't changed anything in the C++ backend

@NicholasFan235 would it be okay with you if we also did this to keep things consistent? Happy to do it myself off your latest version to avoid conflicts

2022-01-20 12:05 UTC, KCGallagher commented
This commit contains the same changes of the cEpiabm backend  - can be easily reverted if we don't want it but hasn't broken anything!

2022-01-24 14:29 UTC, merged