Raise missing households error (Issue #26)
SABS-R3-Epidemiology/epiabm pull request #62
Opened 2022-02-17 12:45 UTC by KCGallagher

For info on the issue this resolves, see issue #26.

We already have a separate [function](https://github.com/SABS-R3-Epidemiology/epiabm/blob/91b775128bffadea844035b8bf6b3c44480489b4/pyEpiabm/pyEpiabm/routine/toy_population_config.py#L85) which is [optionally called](https://github.com/SABS-R3-Epidemiology/epiabm/blob/91b775128bffadea844035b8bf6b3c44480489b4/pyEpiabm/pyEpiabm/routine/toy_population_config.py#L77) if the household number is specified.

I have added a check in the household_sweep, that raises an error if households are missing. Hopefully this resolves all the issues we had with this at the end of last term.

2022-02-17 21:00 UTC, Elizabeth-Hayman commented
Really like this functionality, and whoever changed the if_household boolean into the if num_households>0
Both really improve the code :)

2022-02-17 23:24 UTC, KCGallagher commented
> Really like this functionality, and whoever changed the if_household boolean into the if num_households>0 Both really improve the code :)

ahaha that was me too a while ago, thanks!

2022-02-22 13:31 UTC, rcw5890 requested changes

2022-02-22 13:31 UTC, rcw5890 commented on pyEpiabm/pyEpiabm/sweep/household_sweep.py
> +                    raise AttributeError(f"{infector} is not part of a"
```suggestion
                    raise AttributeError(f"{infector} is not part of a "
```

2022-02-22 14:22 UTC, rcw5890 approved these changes
Thanks

2022-02-22 14:22 UTC, merged